feat: реализовать Сервис статистики
alex1261bat/java-explore-with-me pull request #2
Opened 2023-03-13 18:17 UTC by alex1261bat

2023-03-14 16:40 UTC, alexache requested changes

2023-03-14 16:40 UTC, alexache commented on statistic/statistic-dto/pom.xml
> +            <version>1.18.24</version>
Версии библиотек должны быть указаны только в родительском модуле

2023-03-14 16:40 UTC, alexache commented on statistic/statistic-server/pom.xml
> +            <version>1.5.3.Final</version>
Номера версии только в родительском модуле

2023-03-14 16:40 UTC, alexache commented on statistic/statistic-server/pom.xml
> +            <version>0.0.1-SNAPSHOT</version>
Лучше делать через переменные
            <version>${project.version}</version>

2023-03-14 16:40 UTC, alexache commented on statistic/statistic-server/src/main/java/ru/practicum/ewm/statistic/model/HitEndpoint.java
> +        return Objects.equals(app, current.app) &&
Не стоит так писать equals для JPA моделей, это сложная тема, но лучше ничего кроме id не использовать

2023-03-14 16:40 UTC, alexache commented on statistic/statistic-server/src/main/java/ru/practicum/ewm/statistic/service/StatisticService.java
> +    public HitEndpointDto saveStatistic(HitEndpoint hitEndpoint) {
На вход модель  - на выход ДТО, не логично. Пусть либо сервис, либо контроллер будет заниматься вызовом маппера

2023-03-14 17:48 UTC, alex1261bat commented on statistic/statistic-dto/pom.xml
> +            <version>1.18.24</version>
исправлено

2023-03-14 17:58 UTC, alex1261bat commented on statistic/statistic-server/pom.xml
> +            <version>0.0.1-SNAPSHOT</version>
исправлено

2023-03-14 18:10 UTC, alex1261bat commented on statistic/statistic-server/src/main/java/ru/practicum/ewm/statistic/model/HitEndpoint.java
> +        return Objects.equals(app, current.app) &&
исправлено

2023-03-14 18:16 UTC, alex1261bat commented on statistic/statistic-server/pom.xml
> +            <version>1.5.3.Final</version>
Зависимость используется только здесь, если убираю версию, то ошибка. Как быть не знаю.

2023-03-14 18:39 UTC, alex1261bat commented on statistic/statistic-server/src/main/java/ru/practicum/ewm/statistic/service/StatisticService.java
> +    public HitEndpointDto saveStatistic(HitEndpoint hitEndpoint) {
исправлено

2023-03-15 13:51 UTC, alexache commented on statistic/statistic-server/pom.xml
> +            <version>1.5.3.Final</version>
Зависимости указываются в родительском модуле с помощью dependencyManagement

2023-03-15 13:52 UTC, alexache requested changes

2023-03-15 13:52 UTC, alexache commented on statistic/statistic-server/pom.xml
>              <version>1.5.3.Final</version>
Ответил на комментарий о том, как этого добиться

2023-03-15 14:16 UTC, anzerdev commented on statistic/statistic-server/pom.xml
>              <version>1.5.3.Final</version>
спасибо за разъяснения, вроде бы получилось

2023-03-15 14:59 UTC, alexache approved these changes

2023-03-15 16:52 UTC, merged