Main svc
alex1261bat/java-explore-with-me pull request #5
Opened 2023-03-20 13:09 UTC by alex1261bat

2023-03-21 16:43 UTC, alexache requested changes

2023-03-21 16:43 UTC, alexache commented on service/pom.xml
> +            <version>1.5.3.Final</version>
Версии библиотек должны быть указаны только в родительском модуле

2023-03-21 16:43 UTC, alexache commented on service/pom.xml
> +                <version>1.1.3</version>
Как и версии плагинов - тоже в родительском модуле

2023-03-21 16:43 UTC, alexache commented on service/src/main/java/ru/practicum/service/category/dto/CategoryListDto.java
> +public class CategoryListDto {
Точно ли нужен такой класс? Можно ведь и просто List использовать как он есть

2023-03-21 16:43 UTC, alexache commented on service/src/main/java/ru/practicum/service/category/model/Category.java
> +        return getClass().hashCode();
Хэшкод тоже лучше только по айди считать, чтобы ничего не сломать для особенных классов, как JPA модели

2023-03-21 16:43 UTC, alexache commented on service/src/main/java/ru/practicum/service/event/model/Event.java
> +    private Set<Request> requests;
(вопрос) Действительно ли нужны эти поля в сервисе?

2023-03-21 16:43 UTC, alexache commented on service/src/main/java/ru/practicum/service/event/model/Event.java
> +    private Integer confirmedRequests = 0;
Это не должно храниться в данной таблице - вместо этого нужно получать запросом в момент получения события (и избегать запросов в цикле)

2023-03-21 16:43 UTC, alexache commented on service/src/main/java/ru/practicum/service/event/model/Event.java
> +    private Long views = 0L;
Это тоже не должно храниться в базе, а запрашиваться в сервисе статистики

2023-03-21 16:43 UTC, alexache commented on service/src/main/java/ru/practicum/service/event/service/EventServiceImp.java
> +                            event.setConfirmedRequests(event.getConfirmedRequests() + 1);
Как и писал - так делать не нужно. Нужно получить количество подтвержденных заявок перед проходом по списку, а затем отслеживать, если во время обработки этих запросов уже превысим лимит

2023-03-21 16:43 UTC, alexache commented on service/src/main/java/ru/practicum/service/event/service/EventServiceImp.java
> +                });
А где сохранение?

2023-03-21 16:43 UTC, alexache commented on service/src/main/java/ru/practicum/service/event/service/EventServiceImp.java
> +        serviceStatsClient.postStatistic(httpServletRequest, "ewm-service");
отправка статистики есть, а использование?

2023-03-21 16:43 UTC, alexache commented on stats/pom.xml
> +	<dependencyManagement>
Жто должно быть в родительском модуле

2023-03-21 16:43 UTC, alexache commented on stats/pom.xml
> +			<version>3.0</version>
Не должно быть версий здесь

2023-03-21 16:43 UTC, alexache commented on stats/stats-server/src/main/resources/schema.sql
> +DROP TABLE IF EXISTS hits CASCADE;
Сервис статистики должен был быть сделан на прошлом этапе, откуда столько новых правок?

2023-03-21 17:33 UTC, anzerdev commented on service/pom.xml
> +            <version>1.5.3.Final</version>
исправлено

2023-03-21 17:42 UTC, alex1261bat commented on stats/pom.xml
> +	<dependencyManagement>
исправлено

2023-03-21 17:43 UTC, anzerdev commented on stats/pom.xml
> +			<version>3.0</version>
исправлено

2023-03-21 17:43 UTC, alex1261bat commented on stats/stats-server/src/main/resources/schema.sql
> +DROP TABLE IF EXISTS hits CASCADE;
невнимательность, кривые руки и в связи с этим многократная помощь зала привели к этому((((

2023-03-21 17:57 UTC, alex1261bat commented on service/pom.xml
> +                <version>1.1.3</version>
исправлено

2023-03-21 18:10 UTC, anzerdev commented on service/src/main/java/ru/practicum/service/category/model/Category.java
> +        return getClass().hashCode();
исправлено

2023-03-21 18:19 UTC, alex1261bat commented on service/src/main/java/ru/practicum/service/category/dto/CategoryListDto.java
> +public class CategoryListDto {
исправлено

2023-03-21 18:23 UTC, anzerdev commented on service/src/main/java/ru/practicum/service/event/model/Event.java
> +    private Long views = 0L;
исправлено

2023-03-21 18:24 UTC, anzerdev commented on service/src/main/java/ru/practicum/service/event/model/Event.java
> +    private Integer confirmedRequests = 0;
исправлено

2023-03-21 18:28 UTC, alex1261bat commented on service/src/main/java/ru/practicum/service/event/model/Event.java
> +    private Set<Request> requests;
исправлено

2023-03-21 19:52 UTC, anzerdev commented on service/src/main/java/ru/practicum/service/event/service/EventServiceImp.java
> +                            event.setConfirmedRequests(event.getConfirmedRequests() + 1);
исправлено

2023-03-21 20:20 UTC, alex1261bat commented on service/src/main/java/ru/practicum/service/event/service/EventServiceImp.java
> +                });
исправлено

2023-03-21 20:40 UTC, alex1261bat commented on service/src/main/java/ru/practicum/service/event/service/EventServiceImp.java
> +        serviceStatsClient.postStatistic(httpServletRequest, "ewm-service");
исправлено

2023-03-23 18:29 UTC, alexache requested changes

2023-03-23 18:29 UTC, alexache commented on service/src/main/java/ru/practicum/service/event/service/EventServiceImp.java
> +                eventShortDto.setViews(serviceStatsClient.getStatistic(eventShortDto.getId())));
Это запрос к сервису статистики в цикле, этого нужно избегать. Нужен один запрос по списку событий

2023-03-23 18:29 UTC, alexache commented on service/src/main/java/ru/practicum/service/event/service/EventServiceImp.java
> +            booleanBuilder.and((QEvent.event.participantLimit.eq(0)));
А куда потеряли условие о том, что событие должно быть доступно для бронирования

2023-03-23 18:29 UTC, alexache commented on service/src/main/java/ru/practicum/service/event/service/EventServiceImp.java
>                                  request.setStatus(RequestStatus.CONFIRMED);
Если мы подтверждаем какую-то заявку, то количество доступных мест должно сокращаться?

2023-03-23 18:29 UTC, alexache commented on service/src/main/java/ru/practicum/service/event/service/EventServiceImp.java
> +                        requestRepository.save(requestMapper.mapToRequest(requestDto));
Не стоит делать запросы к базе в цикле

2023-03-23 19:19 UTC, alex1261bat commented on service/src/main/java/ru/practicum/service/event/service/EventServiceImp.java
> +            booleanBuilder.and((QEvent.event.participantLimit.eq(0)));
исправлено

2023-03-23 19:37 UTC, alex1261bat commented on service/src/main/java/ru/practicum/service/event/service/EventServiceImp.java
>                                  request.setStatus(RequestStatus.CONFIRMED);
исправлено

2023-03-23 20:16 UTC, alex1261bat commented on service/src/main/java/ru/practicum/service/event/service/EventServiceImp.java
> +                        requestRepository.save(requestMapper.mapToRequest(requestDto));
исправлено

2023-03-23 20:27 UTC, alex1261bat commented on service/src/main/java/ru/practicum/service/event/service/EventServiceImp.java
> +                eventShortDto.setViews(serviceStatsClient.getStatistic(eventShortDto.getId())));
исправлено

2023-03-25 08:08 UTC, alexache requested changes

2023-03-25 08:08 UTC, alexache commented on service/src/main/java/ru/practicum/service/event/service/EventServiceImp.java
> +                    eventShortDto.setViews(serviceStatsClient.getStatistic(eventShortDto.getId()));
Это все еще запрос к сервису статистики в цикле. Нужен один запрос по списку ивентов

2023-03-25 08:08 UTC, alexache commented on service/src/main/java/ru/practicum/service/event/service/EventServiceImp.java
> +                                event.setParticipantLimit(event.getParticipantLimit() - 1);
Немного не это имел в виду - лимит на количество мест в событии не должен меняться. Нужно просто остлеживать количество уже подтвержденных заявок, то есть eventConfirmedRequests

2023-03-25 17:57 UTC, alex1261bat commented on service/src/main/java/ru/practicum/service/event/service/EventServiceImp.java
> +                    eventShortDto.setViews(serviceStatsClient.getStatistic(eventShortDto.getId()));
исправлено

2023-03-25 18:29 UTC, alex1261bat commented on service/src/main/java/ru/practicum/service/event/service/EventServiceImp.java
> +                                event.setParticipantLimit(event.getParticipantLimit() - 1);
исправлено

2023-03-26 19:10 UTC, alexache requested changes

2023-03-26 19:10 UTC, alexache commented on service/src/main/java/ru/practicum/service/event/service/EventServiceImp.java
> +    private long getEventViews(Long eventId) {
Попытка исправления есть, но что поменялось? 
Этот метод так и вызывается в цикле - то есть на 20 событий 20 вызовов в сервис статистику. К тому же получение статистики всех возможных событий выглядит странно,
Как должно быть?

- Формируешь список событий
- получаешь для них URI
- вызываешь клиент статистики с этим списком URI  (API самого сервиса стастистики принимает список uris, клиент надо доработать)
- получаешь список объектов с просмотрами
- формируешь из этого списка мапу - eventId -> количество просмотров - обходя однократно список и вытаскивая айди
- в цикле по событиям подставляешь значения прсомотров из мапы

2023-03-28 19:22 UTC, alexache approved these changes

2023-03-29 13:10 UTC, merged